### ISSUE TITLE
Links Incorrectos en el mail de bienvenida

### ISSUE THREAD

**Issue by akanner** [cientopolis/collaboratory-frontend#3]
En el texto de mail de bienvenida (el que se envía luego de registrarte) aparecen varios links que apuntan a diversas secciones del sitio. El problema es que dichos links están apuntando a zooniverse y no a colaboratorio.

EJ About:

Link Correcto: http://ec2-52-196-4-55.ap-northeast-1.compute.amazonaws.com/about
Link en el mail: https://www.zooniverse.org/about

Esto mismo sucede con todos los links en el texto del mail.

**Comment by Crentist** [comment]
Gracias Agus. Esto está incluído en la traducción del mail de bienvenida en el otro repo (github.com/cientopolis/collaboratory).
